kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-default-service-account
subjects:
  - kind: ServiceAccount
    namespace: kube-system  # SAMPLE
    name: hyppo-monitor  # SAMPLE
roleRef:
  kind: ClusterRole
  name: required-access-hyppo
  apiGroup: rbac.authorization.k8s.io
