version: '2'

services:
    grafana:
        image: matisq/grafana:latest
        ports:
            - 80:3000
        environment:
            GF_INSTALL_PLUGINS: "abhisant-druid-datasource,alexanderzobnin-zabbix-app,bosun-app,bosun-datasource,briangann-gauge-panel,crate-datasource,digiapulssi-breadcrumb-panel,fastweb-openfalcon-datasource,fetzerch-sunandmoon-datasource,foursquare-clouderamanager-datasource,grafana-clock-panel,grafana-example-app,grafana-influxdb-08-datasource,grafana-kairosdb-datasource,grafana-piechart-panel,grafana-simple-json-datasource,grafana-worldmap-panel,gridprotectionalliance-openhistorian-datasource,gridprotectionalliance-osisoftpi-datasource,hawkular-datasource,jdbranham-diagram-panel,kentik-app,mtanda-heatmap-epoch-panel,mtanda-histogram-panel,ns1-app,opennms-datasource,percona-percona-app,praj-ams-datasource,rackerlabs-blueflood-datasource,raintank-snap-app,raintank-worldping-app,ryantxu-ajax-panel,savantly-heatmap-panel,sileht-gnocchi-datasource,sraoss-sunburst-panel,stagemonitor-elasticsearch-app,udoprog-heroic-datasource,voxter-app"
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
            GF_SECURITY_SECRET_KEY: grafana
            GF_USERS_ALLOW_SIGN_UP: "true"
            GF_USERS_ALLOW_ORG_CREATE: "true"
            GF_AUTH_ANONYMOUS_ENABLED: "true"
            GF_AUTH_ANONYMOUS_ORG_NAME: grafana
            GF_DASHBOARDS_JSON_ENABLED: "true"
            GF_DASHBOARDS_JSON_PATH: /opt/grafana
        restart: always
        networks:
            - internal
        volumes:
            - grafana-lib-data:/var/lib/grafana
            - grafana-log-data:/var/log/grafana

    influxdb:
        image: matisq/influxdb:latest
        environment:
            INFLUX_DATABASE: "snap"
            INLFUX_ADMIN_USER: "grafana"
            INFLUX_ADMIN_PASS: "grafana"
        restart: always
        networks:
            - internal
        volumes:
            - influx-data:/var/lib/influxdb

    hyppo-monitor:
        build: .
        volumes:
            - /lib/modules:/lib/modules:ro
            - /usr/src:/usr/src:ro
            - /sys/kernel/debug:/sys/kernel/debug:ro
            - /proc:/host/proc:ro
            - ./snap_task/single_node_compose:/opt/snap/tasks:ro
        privileged: true
        restart: always
        networks:
           - internal

networks:
    internal:
        driver: bridge

volumes:
    influx-data:
    grafana-lib-data:
    grafana-log-data:
